version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: todo-db
    environment:
      POSTGRES_USER: sude
      POSTGRES_PASSWORD: postgresude123
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: dev.backend.Dockerfile
    container_name: todo-backend
    environment:
      DB_HOST: database
      DB_USER: sude
      DB_PASSWORD: postgresude123
      DB_NAME: tododb
      DB_PORT: 5432
      JWT_SECRET: sude-gizli
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: dev.frontend.Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
